/* RLR · Ricardo López Reyero — la galería de Mina: 50 imágenes y 50 GIF escogidos a mano entre lo que hace el generador.
   Cada renglón es una receta: e = figura · p = gemas · f = fondo · s = semilla · m = movimiento. La imagen se pinta en el momento con arte.js. */
'use strict';
window.GALERIA = {
  img: [
    { e: "mandala", p: "joyas", f: "presion", s: 290374 },
    { e: "corona", p: "todas", f: "noche", s: 561943 },
    { e: "espiral", p: "joyas", f: "noche", s: 740635 },
    { e: "panal", p: "joyas", f: "noche", s: 385573 },
    { e: "flor", p: "joyas", f: "presion", s: 325980 },
    { e: "rombo", p: "corteza", f: "tierra", s: 523389 },
    { e: "caleidoscopio", p: "joyas", f: "jade", s: 141994 },
    { e: "sol", p: "oro", f: "atardecer", s: 640144 },
    { e: "mandala", p: "joyas", f: "noche", s: 572288 },
    { e: "corona", p: "todas", f: "tierra", s: 298360 },
    { e: "espiral", p: "acuifero", f: "acuifero", s: 898000 },
    { e: "panal", p: "joyas", f: "presion", s: 307827 },
    { e: "flor", p: "joyas", f: "noche", s: 646876 },
    { e: "rombo", p: "cristalera", f: "cristalera", s: 14665 },
    { e: "caleidoscopio", p: "cavernas", f: "tierra", s: 595598 },
    { e: "mandala", p: "todas", f: "cristalera", s: 310824 },
    { e: "corona", p: "todas", f: "jade", s: 926630 },
    { e: "espiral", p: "cavernas", f: "jade", s: 398249 },
    { e: "panal", p: "cristalera", f: "cristalera", s: 393557 },
    { e: "flor", p: "acuifero", f: "atardecer", s: 748656 },
    { e: "rombo", p: "joyas", f: "presion", s: 779845 },
    { e: "caleidoscopio", p: "oro", f: "presion", s: 337787 },
    { e: "mandala", p: "acuifero", f: "atardecer", s: 162098 },
    { e: "corona", p: "todas", f: "acuifero", s: 463704 },
    { e: "espiral", p: "cristalera", f: "cristalera", s: 238481 },
    { e: "panal", p: "acuifero", f: "acuifero", s: 310664 },
    { e: "flor", p: "oro", f: "tierra", s: 807489 },
    { e: "rombo", p: "acuifero", f: "acuifero", s: 180328 },
    { e: "caleidoscopio", p: "acuifero", f: "acuifero", s: 379023 },
    { e: "mandala", p: "acuifero", f: "acuifero", s: 99571 },
    { e: "corona", p: "todas", f: "presion", s: 672033 },
    { e: "espiral", p: "oro", f: "presion", s: 927814 },
    { e: "panal", p: "oro", f: "atardecer", s: 157942 },
    { e: "flor", p: "cristalera", f: "noche", s: 746455 },
    { e: "rombo", p: "oro", f: "atardecer", s: 546219 },
    { e: "caleidoscopio", p: "todas", f: "noche", s: 258098 },
    { e: "mandala", p: "cavernas", f: "jade", s: 580383 },
    { e: "corona", p: "todas", f: "cristalera", s: 615275 },
    { e: "espiral", p: "corteza", f: "tierra", s: 10269 },
    { e: "panal", p: "corteza", f: "tierra", s: 55943 },
    { e: "rombo", p: "joyas", f: "cristalera", s: 655089 },
    { e: "caleidoscopio", p: "corteza", f: "jade", s: 67526 },
    { e: "mandala", p: "cristalera", f: "noche", s: 547348 },
    { e: "espiral", p: "joyas", f: "jade", s: 933930 },
    { e: "panal", p: "todas", f: "noche", s: 807892 },
    { e: "mandala", p: "oro", f: "atardecer", s: 23095 },
    { e: "espiral", p: "cristalera", f: "acuifero", s: 384790 },
    { e: "panal", p: "joyas", f: "acuifero", s: 228956 },
    { e: "mandala", p: "corteza", f: "jade", s: 96042 },
    { e: "mandala", p: "cavernas", f: "noche", s: 751706 },
  ],
  gif: [
    { e: "mandala", p: "joyas", f: "presion", s: 863373, m: "giro" },
    { e: "corona", p: "todas", f: "cristalera", s: 559505, m: "cascada" },
    { e: "espiral", p: "joyas", f: "noche", s: 599389, m: "giro" },
    { e: "panal", p: "joyas", f: "noche", s: 175244, m: "latido" },
    { e: "flor", p: "joyas", f: "presion", s: 42558, m: "giro" },
    { e: "rombo", p: "cristalera", f: "cristalera", s: 316435, m: "cascada" },
    { e: "caleidoscopio", p: "joyas", f: "jade", s: 944046, m: "giro" },
    { e: "sol", p: "oro", f: "atardecer", s: 644107, m: "giro" },
    { e: "mandala", p: "joyas", f: "noche", s: 667688, m: "vaiven" },
    { e: "corona", p: "todas", f: "tierra", s: 187071, m: "latido" },
    { e: "espiral", p: "cavernas", f: "jade", s: 333408, m: "latido" },
    { e: "panal", p: "joyas", f: "presion", s: 19937, m: "ola" },
    { e: "flor", p: "joyas", f: "noche", s: 262112, m: "vaiven" },
    { e: "rombo", p: "joyas", f: "presion", s: 692053, m: "latido" },
    { e: "caleidoscopio", p: "cristalera", f: "cristalera", s: 740867, m: "vaiven" },
    { e: "sol", p: "oro", f: "presion", s: 870362, m: "cascada" },
    { e: "mandala", p: "todas", f: "cristalera", s: 448574, m: "giro" },
    { e: "corona", p: "todas", f: "jade", s: 2637, m: "ola" },
    { e: "espiral", p: "cristalera", f: "cristalera", s: 608581, m: "ola" },
    { e: "panal", p: "cristalera", f: "cristalera", s: 27069, m: "cascada" },
    { e: "flor", p: "acuifero", f: "atardecer", s: 760719, m: "ola" },
    { e: "rombo", p: "acuifero", f: "acuifero", s: 991003, m: "vaiven" },
    { e: "caleidoscopio", p: "cavernas", f: "tierra", s: 834346, m: "latido" },
    { e: "mandala", p: "acuifero", f: "atardecer", s: 74944, m: "cascada" },
    { e: "corona", p: "todas", f: "acuifero", s: 846979, m: "vaiven" },
    { e: "espiral", p: "oro", f: "presion", s: 967493, m: "giro" },
    { e: "panal", p: "acuifero", f: "acuifero", s: 290222, m: "vaiven" },
    { e: "flor", p: "oro", f: "tierra", s: 473238, m: "giro" },
    { e: "rombo", p: "oro", f: "atardecer", s: 906145, m: "ola" },
    { e: "caleidoscopio", p: "oro", f: "presion", s: 602835, m: "giro" },
    { e: "mandala", p: "acuifero", f: "acuifero", s: 950063, m: "giro" },
    { e: "corona", p: "todas", f: "presion", s: 826812, m: "cascada" },
    { e: "espiral", p: "corteza", f: "tierra", s: 992038, m: "cascada" },
    { e: "panal", p: "oro", f: "atardecer", s: 563028, m: "latido" },
    { e: "rombo", p: "joyas", f: "cristalera", s: 682398, m: "cascada" },
    { e: "caleidoscopio", p: "acuifero", f: "acuifero", s: 599792, m: "vaiven" },
    { e: "mandala", p: "cavernas", f: "jade", s: 701925, m: "latido" },
    { e: "corona", p: "todas", f: "cristalera", s: 989053, m: "latido" },
    { e: "espiral", p: "joyas", f: "jade", s: 325392, m: "giro" },
    { e: "panal", p: "corteza", f: "tierra", s: 377968, m: "ola" },
    { e: "caleidoscopio", p: "joyas", f: "presion", s: 646994, m: "latido" },
    { e: "mandala", p: "cristalera", f: "noche", s: 192571, m: "ola" },
    { e: "espiral", p: "oro", f: "atardecer", s: 279803, m: "latido" },
    { e: "panal", p: "todas", f: "noche", s: 14821, m: "cascada" },
    { e: "caleidoscopio", p: "corteza", f: "jade", s: 44602, m: "giro" },
    { e: "mandala", p: "oro", f: "atardecer", s: 617271, m: "giro" },
    { e: "espiral", p: "cristalera", f: "acuifero", s: 779965, m: "ola" },
    { e: "panal", p: "joyas", f: "acuifero", s: 287378, m: "vaiven" },
    { e: "mandala", p: "corteza", f: "jade", s: 791998, m: "vaiven" },
    { e: "mandala", p: "joyas", f: "acuifero", s: 521677, m: "giro" },
  ],
  // De aquí salen las que se hacen solas al seguir bajando: figura → [gemas, fondo] que se llevan bien
  pares: {"mandala": [["joyas", "presion"], ["joyas", "noche"], ["todas", "cristalera"], ["todas", "tierra"], ["acuifero", "atardecer"], ["acuifero", "acuifero"], ["cavernas", "jade"], ["cristalera", "noche"], ["oro", "atardecer"], ["corteza", "jade"], ["joyas", "acuifero"], ["cavernas", "noche"]], "corona": [["todas", "cristalera"], ["todas", "noche"], ["todas", "tierra"], ["todas", "atardecer"], ["todas", "jade"], ["todas", "acuifero"], ["todas", "presion"]], "espiral": [["joyas", "noche"], ["acuifero", "acuifero"], ["cavernas", "jade"], ["cristalera", "cristalera"], ["oro", "presion"], ["corteza", "tierra"], ["joyas", "jade"], ["oro", "atardecer"], ["cristalera", "acuifero"], ["cavernas", "tierra"]], "panal": [["joyas", "noche"], ["joyas", "presion"], ["cristalera", "cristalera"], ["cavernas", "jade"], ["acuifero", "acuifero"], ["oro", "atardecer"], ["corteza", "tierra"], ["todas", "noche"], ["joyas", "acuifero"], ["cavernas", "noche"]], "flor": [["cristalera", "cristalera"], ["cavernas", "jade"], ["joyas", "presion"], ["joyas", "noche"], ["acuifero", "atardecer"], ["oro", "tierra"], ["corteza", "noche"], ["cristalera", "noche"], ["joyas", "jade"]], "rombo": [["corteza", "tierra"], ["joyas", "noche"], ["cristalera", "cristalera"], ["cavernas", "jade"], ["joyas", "presion"], ["acuifero", "acuifero"], ["oro", "atardecer"], ["todas", "noche"], ["joyas", "cristalera"]], "caleidoscopio": [["joyas", "jade"], ["joyas", "noche"], ["cristalera", "cristalera"], ["cavernas", "tierra"], ["oro", "presion"], ["acuifero", "acuifero"], ["todas", "noche"], ["joyas", "presion"], ["corteza", "jade"]]},
  figuras: ['mandala', 'mandala', 'mandala', 'corona', 'corona', 'espiral', 'espiral', 'panal', 'panal', 'flor', 'flor', 'rombo', 'rombo', 'caleidoscopio'],
};
